### ISSUE TITLE
Sorting Machine throws IOOB when in full match mode

### ISSUE THREAD

**Issue by jjc54** [elytra/Teckle#12]
MC: 1.12
Forge: forge-14.21.1.2420
Teckle: teckle-1.12-1.338
Issue: crash when cycling sorting machine modes.
Crash Report: https://gist.github.com/whitestarx0312/aae2673496b519071f0e68ab892da07f

**Comment by darkevilmac** [comment]
Was this inline or just next to an inventory?

**Comment by jjc54** [comment]
hmm I had two sorting machines connected to the backside of a double chest.

**Comment by darkevilmac** [comment]
Was the machine already sorting when you changed the mode or had it not started anything yet? Also, what pull mode was it in?

**Comment by darkevilmac** [comment]
On a different note, one sorting machine should be enough for most use cases.

**Comment by jjc54** [comment]
No the machine wasn't sorting anything. I don't think I had tweaked the pull mode so it was probably in whatever the default mode is. And yeah I thought one sorting machine was enough, just wasn't sure at the time.

**Comment by darkevilmac** [comment]
I couldn't reproduce the issue but that commit should fix it, creating a new release.

**Comment by darkevilmac** [comment]
@whitestarx0312 https://github.com/elytra/Teckle/releases/tag/1.12-3.342
