### ISSUE TITLE
Changing Dimension causes Exception in server tick loop

### ISSUE THREAD

**Issue by SwornGamer** [elytra/Teckle#14]
- Teckle version 1.12-3.342
- Minecraft version 1.12
- Forge version 14.21.1.2443
- Crash log - https://pastebin.com/Mafvst3C

I'll be honest I'm not sure what's causing this crash, but it happens when I'm changing dimension from the overworld to the Aroma mining dimension.

**Comment by darkevilmac** [comment]
On second thought that might not work, try this build and see if the problem still occurs. https://ci.elytradev.com/job/elytra/job/Teckle/job/1.12/54/artifact/build/libs/teckle-1.12-3.344.jar

**Comment by SwornGamer** [comment]
I used the build you gave me and it works fantastic. Thanks!
