### ISSUE TITLE
Items already in tubes are no longer visible after reloading the world

### ISSUE THREAD

**Issue by dblsaiko** [elytra/Teckle#15]
Using Minecraft 1.12.1, Teckle version git-3e6dac6, Forge 14.22.0.2452

This is purely clientside, items still travel through the network, just not visibly.

**Comment by dblsaiko** [comment]
Also, as a sidenote: Is there a maven that provides builds of Teckle?

**Comment by darkevilmac** [comment]
There's not, I'll see if I can convince @unascribed to set that up.
Currently you just have to grab from ci.

**Comment by darkevilmac** [comment]
This is a known bug, not sure about fixing it as its purely a visual bug.
