### ISSUE TITLE
Game freezes if you load the world while items are being pulled out

### ISSUE THREAD

**Issue by dblsaiko** [elytra/Teckle#16]
Using Minecraft 1.12.1, Teckle version git-3e6dac6, Forge 14.22.0.2452

Crash log: https://gist.github.com/MRebhan/a01f55d45e9dc8d56245765b5ad4f39b

This might actually be my Sortron block causing it as I was using it to continuously pull out items. I doubt it though, since the stacktrace doesn't show my mod at all.

EDIT: ~~Looks like this is indeed caused by my mod, I don't know by what though. It doesn't happen with the sorting machine. Do you have an idea?~~

EDIT2: It does happen with the sorting machine too. Same stack trace.

**Comment by darkevilmac** [comment]
What mode was the sorting machine in?

**Comment by dblsaiko** [comment]
Full Stack & Automatic

EDIT: Here's a demonstration: https://gfycat.com/DefiantObeseHoiho

**Comment by darkevilmac** [comment]
Just reproduced, I'll try and get a fix out in the next little while but I'm heading to sleep in just a minute.

Looks like the issue can also be produced by changing the default route colour while an item is being ejected as well. Will take a look at this in the morning.
