### ISSUE TITLE
Tubes don't act "round robin"

### ISSUE THREAD

**Issue by dblsaiko** [elytra/Teckle#17]
Using Minecraft 1.12.1, Teckle version git-1cc9a5d, Forge 14.22.0.2452

Shouldn't the tubes evenly distribute the items?
Demonstration: https://gfycat.com/PerkyFlawedBackswimmer

**Comment by darkevilmac** [comment]
Can't reproduce. Also please use CI version numbers (eg 1.12-4.345). https://ci.elytradev.com/job/elytra/job/Teckle/job/1.12/

https://gfycat.com/JaggedRaggedGlowworm

**Comment by darkevilmac** [comment]
Hmm, actually this might be because of the colour tags. Adding colours to my sorting machine and trying again...

**Comment by darkevilmac** [comment]
Nope, still not happening when I add colours. Round robin ticks and counter stuff is in the network traveller class. If this only happens with your block I'd take a look in there with some breakpoints to determine if you're missing something.

**Comment by dblsaiko** [comment]
Yeah you're right, whoops. I should test with your blocks too next time…

**Comment by darkevilmac** [comment]
Heh.
