### ISSUE TITLE
Chisel Recipe Conflict

### ISSUE THREAD

**Issue by MasterGeneral156** [elytra/Teckle#19]
As of Teckel Version 1.12-1.338, the Preciso Blade recipe conflicts with the Iron Chisel recipe from... well, Chisel. I've got no idea if this has since been fixed (Running it on a server, haven't got time for the mod updates yet today)  
  
In either case, probably something you should know. Apologies if this has been fixed already.

**Comment by exaskye** [comment]
You've now made it more likely to collide with recipes from other mods. :100:

I'd suggest changing the recipe to a brass ingot and an iron ingot diagonal.
