### ISSUE TITLE
Transposer doesn't pull

### ISSUE THREAD

**Issue by dblsaiko** [elytra/Teckle#21]
Using Minecraft 1.12.2, Forge 14.22.0.2463, Teckle 1.12-5.378-SNAPSHOT.

When activating a transposer, it doesn't pull an "OH SHIT TECKLE BROKE" message appears in the log. The item might or might not get removed from the attached inventory.

Log: https://hastebin.com/ejabicapuw.md

**Comment by darkevilmac** [comment]
Just merging this with #20 and making it more general.
