### ISSUE TITLE
Make Teckle use Vanilla Materials?

### ISSUE THREAD

**Issue by abculatter2** [elytra/Teckle#23]
I don't really see much reason for this mod to require its own world generation, or any kind of materials beyond what's available in vanilla. At very least, it would be nice to make it not require Substratum, so that we can modtweak it ourselves to use vanilla materials without needing to add bloat to a modpack...

**Comment by darkevilmac** [comment]
This argument could be made for pretty much any mod that exists. This will not be changing.

**Comment by asiekierka** [comment]
Also, the mod does not require Substratum.

**Comment by darkevilmac** [comment]
It requires a mod that adds tin, copper, and silver. Smores would work, most modpacks have the ores that I would end up providing anyway.

I don't add my own ores because every other mod under the sun has done that already.

**Comment by abculatter2** [comment]
Why not remove that requirement, and make the mod just not generate recipes that require stuff that's not there?

**Comment by darkevilmac** [comment]
If you want your own recipes use crafttweaker.

**Comment by abculatter2** [comment]
As I said, in order to use this mod I have to add another mod that adds ores just to be able to get it to load, just so I can then add those recipes. This is pointless, frivolous, and reduces performance, not to mention introduces the potential for cross-mod bugs for a mod that has no point in being there.

**Comment by darkevilmac** [comment]
No you don't, look at the config file.
