### ISSUE TITLE
Implement restriction tubes

### ISSUE THREAD

**Issue by fehrnah** [elytra/Teckle#25]
Restriction tube are tube which act like regular tubes except object routing considers them as an infinite length.

Restriction tubes can be colored as regular tubes.

**Comment by dblsaiko** [comment]
Note: In RP2, they act as if they're 5000 blocks long, not infinite.

**Comment by fehrnah** [comment]
> Note: In RP2, they act as if they're 5000 blocks long, not infinite.

I consider that an implementation detail. For the player it appeared to work as if it was infinite.
