### ISSUE TITLE
Redstonesignal on tubes

### ISSUE THREAD

**Issue by TimGoll** [elytra/Teckle#36]
#### Feature description.
![image](https://user-images.githubusercontent.com/13639408/45474405-008c9700-b73a-11e8-83ac-12c269011902.png)
Like in RP you should be able to transport a redstone signal over the tubes

#### Does this feature involve mod compatability, if so, which mods
No other mods needed

**Comment by adrwa** [comment]
Duplicate of #32

**Comment by TimGoll** [comment]
my bad, sorry!
