### ISSUE TITLE
[Request] Use capabilities for pipe connections

### ISSUE THREAD

**Issue by MRebhan** [elytra/Teckle#5]
It would really help if there was a capability for connections so me and others can easily add other stuff that can connect to pipes (the Sortron comes to mind)

**Comment by darkevilmac** [comment]
I need a bit more information as to what you want to accomplish.

When an item is added to a pipe network it needs to know where it came from, this requires registration of a node in the network done by a neighbouring tube or the block itself.

So to have tubes just allow entry from arbitrary blocks is kind of difficult, I'd need to add a way to prompt a network creation/discovery when you add a custom block.

**Comment by MRebhan** [comment]
I mainly want a way to add blocks such as your Transposer or Filter (or is that already possible by copying those classes and modifying them?)
Probably capabilities aren't the way to go here, I just would like a way to add blocks that utilize the pipe network.

**Comment by darkevilmac** [comment]
A lot of the code needs to be a bit more easy to use, currently most of the
logic to put something into a network is handled directly by the filter or
transposer tile. If you based your code off of the transposer and filters
tile and block you should be fine, but I plan to make it a lot easier in a
future update.

**Comment by MRebhan** [comment]
Alright. Thanks!

**Comment by darkevilmac** [comment]
@MRebhan the last few commits have added some things to make development possible. You need to add IWorldNetworkTile as a capability on your tile entities. And for network references use IWorldNetworkAssistantHolder which is automatically attached to worlds.

**Comment by MRebhan** [comment]
Cool, thanks! I'll check it out
