### ISSUE TITLE
NPE in server tick loop

### ISSUE THREAD

**Issue by marcin212** [elytra/Teckle#8]
- custom build 
- MC 1.11.2
- Forge 13.20.0.2310
- https://gist.github.com/marcin212/81872ee6ce774fc95d162bc475b20e09

Crash is [here](https://github.com/elytra/Teckle/blob/1.11.2/src/main/java/com/elytradev/teckle/common/worldnetwork/common/DropActions.java#L35) because constructor, which is used [here](https://github.com/elytra/Teckle/blob/1.11.2/src/main/java/com/elytradev/teckle/common/worldnetwork/common/DropActions.java#L35) doesn't set [this](https://github.com/elytra/Teckle/blob/1.11.2/src/main/java/com/elytradev/teckle/common/worldnetwork/common/WorldNetworkTraveller.java#L48) field.

**Comment by darkevilmac** [comment]
You need to provide the build number, as well as how to reproduce this issue.

**Comment by marcin212** [comment]
289

**Comment by darkevilmac** [comment]
I'll take a look, but don't expect this to be fixed in 1.11, development is going to be on 1.12 from this point. There's a lot more mod support on that verion.

**Comment by asiekierka** [comment]
>There's a lot more mod support on that verion.

Not yet. Maybe next week.

**Comment by darkevilmac** [comment]
Please see if this issue still happens in recent builds. Closing until issue can be confirmed as still present.
